FROM node:18

WORKDIR /app

COPY . .

RUN echo "Listing /app directory:" && ls -l /app
RUN echo "Checking file type of stockfish:" && file /app/stockfish
RUN chmod +x /app/stockfish
RUN echo "Listing /app after making stockfish executable:" && ls -l /app

RUN npm install

CMD ["node", "server.js"]
