[build]
  builder = "nodejs_18"

  # Ensure stockfish exists and is executable
  build_commands = [
    "echo 'Listing contents of /app directory' && ls -l /app",  # List the files in /app to check stockfish location
    "chmod +x /app/stockfish",  # Grant execute permissions to stockfish
    "echo 'Listing contents of /app directory after chmod' && ls -l /app"  # List the files again to confirm permissions
  ]

[start]
  command = "node server.js"

[env]
  NODE_ENV = "production"
